### PR TITLE
Fix: create targets namespace optimization

### LINKED ISSUE #338: [Bug] New Target Bug
In `New Target`, click `New` beside `Namespace`:

image

The Namespace will be null and `New` become `Submit`:

image

Click again:

image

### PR DESCRIPTION
**Pull request by wangbow**
Signed-off-by: wb-wb665667 <wb-wb665667@alibaba-inc.com>

### Description of your changes
Fixes #338 create targets namespace optimization

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary.
- [x] Run `yarn lint` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### Special notes for your reviewer
image
image

### CODE REVIEW

File: src/pages/TargetList/components/Namespace/index.tsx [hunk 1]
```diff
@@ -116,6 +148,40 @@ class Namespace extends React.Component<Props, State> {
             </Button>
           </div>
         </If>
+        <Dialog
```
Comment (barnettZQG) [inline src/pages/TargetList/components/Namespace/index.tsx:151]: showNameSpaceInput 相关的逻辑移除，namespace 创建完成后select表单自动选中

Comment (wangbow) [reply src/pages/TargetList/components/Namespace/index.tsx:151]: done

**Review by barnettZQG — APPROVED** [review]
